---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fweb70577-deployment
  labels:
    app: fortiweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortiweb
  template:
    metadata:
      labels:
        app: fortiweb
    spec:
      containers:
      - name: fweb70577-container
        image: interbeing/myfmg:fweb70577
        securityContext:
          privileged: true
        ports:
        - containerPort: 8
        - containerPort: 9
        - containerPort: 43
        - containerPort: 22
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: fweb70577-service
  annotations:
    
    service.beta.kubernetes.io/azure-dns-label-name: k8strainingmaster1onarotest
    external-dns.alpha.kubernetes.io/ttl: "60"
   # service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-1234567890abcdef0"
spec:
#  sessionAffinity: ClientIP
  ports:
  - port: 2222 
    name: ssh
    targetPort: 22
  - port: 18443
    name: gui
    targetPort: 43
  - port: 8888
    name: fweb70577-service-8888
    targetPort: 8888
  selector:
    app: fortiweb
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config
data:
  SSH_HOST: "52.71.64.97"
  SSH_PORT: "2222"
  SSH_USERNAME: "admin"
  SSH_NEW_PASSWORD: "Welcome.123"
  FORTIWEBIMAGENAME: "fweb70577"
  FORTIWEBSVCPORT:   "8888"
